// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WareHouse.Infrastructure.DataBase;

#nullable disable

namespace WareHouse.Infrastructure.Migrations
{
    [DbContext(typeof(WareHouseContext))]
    partial class WareHouseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WareHouse.Domain.Models.RackModel", b =>
                {
                    b.Property<Guid>("RackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RackDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RackName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RackX")
                        .HasColumnType("int");

                    b.Property<int>("RackY")
                        .HasColumnType("int");

                    b.Property<int>("TotalPlaces")
                        .HasColumnType("int");

                    b.HasKey("RackId");

                    b.ToTable("RackTable");
                });
#pragma warning restore 612, 618
        }
    }
}
